package dev.interp.gateway.session

import jakarta.validation.Valid
import jakarta.validation.constraints.NotBlank
import jakarta.validation.constraints.Size
import org.springframework.dao.DataAccessResourceFailureException
import org.springframework.http.HttpStatus
import org.springframework.transaction.CannotCreateTransactionException
import org.springframework.web.bind.annotation.ExceptionHandler
import org.springframework.web.bind.annotation.GetMapping
import org.springframework.web.bind.annotation.PathVariable
import org.springframework.web.bind.annotation.PostMapping
import org.springframework.web.bind.annotation.RequestBody
import org.springframework.web.bind.annotation.RequestMapping
import org.springframework.web.bind.annotation.ResponseStatus
import org.springframework.web.bind.annotation.RestController
import java.util.UUID

data class CreateSessionResponse(val sessionId: UUID)

data class SessionResponse(val sessionId: UUID, val lastSeq: Long)

data class UtteranceRequest(
    /** Generated by the client per utterance and reused on retries; makes ingest idempotent. */
    val utteranceId: UUID,
    @field:NotBlank
    @field:Size(max = 2000)
    val text: String,
)

data class UtteranceResponse(val seq: Long, val ingestedAtMs: Long, val duplicate: Boolean)

@RestController
@RequestMapping("/sessions")
class SessionController(private val ingest: IngestService) {

    @PostMapping
    @ResponseStatus(HttpStatus.CREATED)
    fun create(): CreateSessionResponse = CreateSessionResponse(ingest.createSession())

    /** Lets clients (and the load test) check how many utterances a session has. */
    @GetMapping("/{sessionId}")
    fun get(@PathVariable sessionId: UUID): SessionResponse = ingest.find(sessionId)

    @PostMapping("/{sessionId}/utterances")
    @ResponseStatus(HttpStatus.ACCEPTED)
    fun utter(@PathVariable sessionId: UUID, @Valid @RequestBody request: UtteranceRequest): UtteranceResponse {
        val result = ingest.ingest(sessionId, request.utteranceId, request.text)
        return UtteranceResponse(result.seq, result.ingestedAtMs, result.duplicate)
    }

    @ExceptionHandler(SessionNotFoundException::class)
    @ResponseStatus(HttpStatus.NOT_FOUND)
    fun notFound(e: SessionNotFoundException): Map<String, String?> = mapOf("error" to e.message)

    /** Kafka or Postgres unavailable: nothing was committed, retry with the same utteranceId. */
    @ExceptionHandler(
        IngestUnavailableException::class,
        CannotCreateTransactionException::class,
        DataAccessResourceFailureException::class,
    )
    @ResponseStatus(HttpStatus.SERVICE_UNAVAILABLE)
    fun unavailable(): Map<String, String> = mapOf("error" to "temporarily unavailable, retry with the same utteranceId")
}
